name: Effia Checker

on:
  schedule:
    - cron: "0 * * * *"  # toutes les heures
  workflow_dispatch:     # permet de lancer manuellement

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: pip install requests beautifulsoup4

      - name: Run checker
        env:
          EMAIL: ${{ secrets.EMAIL }}
          PASSWORD: ${{ secrets.PASSWORD }}
          RECEIVER: ${{ secrets.RECEIVER }}
        run: python check_effia.py
